TalkTopic.create(content: '恥ずかしかったこと', user_id: 1)
TalkTopic.create(content: '最近起きた奇跡', user_id: 1)
TalkTopic.create(content: '昨日起こったちょっといいこと', user_id: 1)
TalkTopic.create(content: 'すべらない話', user_id: 1)
TalkTopic.create(content: '今までで一番やらかしたこと', user_id: 1)
